### ISSUE TITLE
Gmail list/get threads and drafts

### ISSUE THREAD

**Issue by spyeadon** [pradeep-mishra/google-batch#10]
Does this API give us the option of making batch request for gmail.user.drafts or gmail.users.threads methods of the google Gmail API? Or is it just for batch requests on the gmail.users.messages object? And can I both **list** _and_ **get** messages with this API?

**Comment by pradeep-mishra** [comment]
I think it should.
I have just implemented Google batch call functionality, so ideally it should work with other calls too.

**Comment by spyeadon** [comment]
Yup absolutely worked. Thanks!
