### ISSUE TITLE
latest version not published to npm

### ISSUE THREAD

**Issue by zoellner** [pradeep-mishra/google-batch#5]
npm still shows "0.0.6 is the latest of 6 releases"
Can you please publish the latest code to npm?
Thank you

**Comment by joypeterson** [comment]
+1.  I ran into the bug that was fixed by pull request #4 and I need to be able to install a newer version that includes that fix.

**Comment by zoellner** [comment]
you can specify my forked version for the moment until it gets published to npm (use "zoellner/google-batch" in your package.json as version number)

**Comment by pradeep-mishra** [comment]
Latest code is on npm 0.0.7, thanks for contributing
