### ISSUE TITLE
refresh_token not supported

### ISSUE THREAD

**Issue by aaronyo** [pradeep-mishra/google-batch#9]
Google-batch does not support refresh_tokens.  You must provide a valid access-token.

I'm not sure what the protocol is for exchanging a refresh token for a new access token, but the standard gmail api client seems to do this automagically for all of the api calls I have used, so it was surprising when google batch was failing using the same auth input.

Here's my current work around. Perhaps there is a better one.
1. Create an OAuth2 object with the refresh_token
2. Pass this to a standard gmail api call
(side effect of that call: update the OAuth2 object with a new access_token)
3: Now use google-batch (batch.setAuth(...)) with the the updated OAuth2 object.

**Comment by aaronyo** [comment]
After a bit more thought, I can imagine why you would want to exchange the refresh_token before firing off a batch request to google... I guess the question is: does google's http batch api directly support refresh tokens?

**Comment by pradeep-mishra** [comment]
Yes, that functionality is supported by google node sdk not api call, sdk refresh token if any of its calls failed and then retry again.
and I dont use google sdks http request wrapper to make call, thats why it's failing in our case if the token is expired
